apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::941048012733:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::941048012733:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-GOV7H8SI5SL6
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2021-08-12T15:58:40Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "118909"
  uid: 6aef9c34-0f5d-4033-bcc3-feef7b31f779
